### ISSUE TITLE
Specific properties

### ISSUE THREAD

**Issue by TheRisingSun7** [EugeneKim/SimpleUnityCalendar#1]
Hi, I was wondering if there is a way to make specific days of the calendar different.
What I mean is for example changing the button background for a specific day or changing a subtext inside the button.
Thanks

**Comment by EugeneKim** [comment]
Hi R23N,

I would have a list of button prefabs to differentiate the styles, then pass the specific days of a month in Initialize method of the BodyManager so that the button manager can refer to the prefabs based on the days.

**Comment by TheRisingSun7** [comment]
I've been trying to mess around with the code and implement this, what I'm trying to do is use a different prefab for, let's say, August 2017 onward, so before August 2017 I use a prefab, then from August 2017 onward I use another.
Could you help me with this specific issue?
Thanks a lot

**Comment by EugeneKim** [comment]
That case, the CalendarManager could have prefabs of months and the private method Refresh can control which prefab could be chosen based on current month.
